{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "web-maintenance.fullname" . }}
  labels:
    {{- include "web-maintenance.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.tls }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}

  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "web-maintenance.fullname" . }}
                port:
                  number: {{ .Values.service.port }}

  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ include "web-maintenance.fullname" . }}-tls
  {{- end }}
{{- end }}